apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog

bases:
- ../../../../environments/overlays/3scale

resources:
- user-rolebinding.yaml
- api-url-config-sealed-secret.yaml

patchesStrategicMerge:
- patch.yaml