apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apicast-configuration-url-secret
  namespace: product-catalog
spec:
  encryptedData:
    password: AgCm+yozNkqwdfymZexQ5T/asTlmVBTLVd2z2bPJvpSzA5FnvcidwwLhaX4ln3U7RWpLdQqMQw3zAnWaV1BM7Ziqd9qUGoSBsItKP911ccsppd6NIbQEZyVkQoG6vUBh1dkkHeIzwe+Gb6Ft9Cbwy22WqV/8byOf+ihGgdjsBHpbSIw4pcuIpVoqip6RrLFxhB7ETTnzCfOUYOqP0pXM2p8r/1IE75UzrpkXj/1v+awBNa7QGz3HJ36/J0r8qpnyvU0+WzDDEzQ2HnnMQ+0mIjf0izvWWlqs1+LYLXvZhxumlBZwIodduXRmHSlSwDRggkHDMUpJMhvUQBmPyFW8CYCN0flwCFX7y+4F0ATQPMU3uqSozwi4nZ1uSoRFTRu9zdlzQ3fV2c4PcC0GljCoubScWdo4qvMIJ4gdJ9ZIaiAtbDsT91QbQqdmJs0IvUqLrQdGbjppMMo3jv4P6p6UsMfeSh24mnF18cIO0TkzphPsAOU4uaZc/Yvj9Gi+1khsMDXhlfkh3L5UUANOOYQkZpT5LOpJgdnHFmyadHHbCeCflAwOHO0okZ6zWtw4zU402liK84BkOxb3fUVtwuLKxGKUmsDgHbFajsh93PbLjloP/SYc+t3rgQRfN5uEglr47N8jm7xYfBCVLjehQa3wZ+347lHI6Ozr7hfs9F5+j1BsEAa95nTblonI0I7Xb+5hniSk0v3qjsfuIaEaotS9YLpi1BJjMJhk6A3b2+KJNlJlPOdF9Lyo5Vtalwrnjxq+c+kiSlOOS5anh19cvXjcebE9IKlHAV4WjZsBbONy3J21qVl+ZK3yCDxbQ/WJQg5PlCmyMw==
  template:
    metadata:
      creationTimestamp: null
      name: apicast-configuration-url-secret
      namespace: product-catalog
    type: kubernetes.io/basic-auth

