apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-3scale

bases:
- https://github.com/gnunn-gitops/product-catalog/manifests/app/database/base
- https://github.com/gnunn-gitops/product-catalog/manifests/app/server/base
- https://github.com/gnunn-gitops/product-catalog/manifests/app/client/base
- https://github.com/redhat-canada-gitops/catalog/apicast/overlays/default

resources:
- namespace.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: server
  path: patch-server-deployment.yaml

- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: apicast-prod
  path: patch-apicast-deployment.yaml

- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: apicast-stage
  path: patch-apicast-deployment.yaml

transformers:
- global-labels.yaml