- op: replace
  path: /spec/template/spec/containers/0/image
  value: quay.io/gnunn/client:latest
- op: replace
  path: /metadata/annotations
  value:
    app.openshift.io/connects-to: 3scale-gateway-prod
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/gnunn-gitops/product-catalog-client  
  